### ISSUE TITLE
Improve code style and use factory method pattern

### ISSUE THREAD

**Issue by Tyvrel** [EnQs/JustCalculator#1]
1. https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/core/Main.java#L8-L11
`setVisible` should be last

2. https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/gui/Display.java#L42-L46
I suggest using "Factory Pattern" as below:
```java
private JLabel buildNumericalDisplay() { 
     JLabel numericalDisplay = new JLabel();
     numericalDisplay.setHorizontalAlignment(SwingConstants.RIGHT); 
     numericalDisplay.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED, Color.CYAN, Color.BLUE));
     numericalDisplay.setText("000 000 000,00");
     return numericalDisplay;
 } 

Display(){ 
    this.numericalDisplay = buildNumericalDisplay();
    this.displayPanel = buildDisplayPanel();
}
```
https://en.wikipedia.org/wiki/Factory_method_pattern
https://pl.wikipedia.org/wiki/Metoda_wytw%C3%B3rcza_(wzorzec_projektowy)
3. https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/gui/Display.java#L31-L36
Calculate `Font` first and then set it once to swing component (avoid setting font multiple times)

4.
https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/gui/GUI.java#L67-L73
Looks very hacky. This should be solved by proper configuration of LayoutManager.

5. https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/gui/GUI.java#L34-L39

Use factory method as well

6.
https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/gui/GUI.java#L26-L32
Why are you passing var-args (array) instead string?

**Comment by EnQs** [comment]
> 

>

**Comment by EnQs** [comment]
1. 

> https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/core/Main.java#L8-L11
setVisible should be last

Done

2.


> https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/gui/Display.java#L42-L46
> I suggest using "Factory Pattern" as below:
> ```java
> private JLabel buildNumericalDisplay() { 
>      JLabel numericalDisplay = new JLabel();
>      numericalDisplay.setHorizontalAlignment(SwingConstants.RIGHT); 
>      numericalDisplay.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED, Color.CYAN, Color.BLUE));
>      numericalDisplay.setText("000 000 000,00");
>      return numericalDisplay;
>  } 
> Display(){ 
>     this.numericalDisplay = buildNumericalDisplay();
>     this.displayPanel = buildDisplayPanel();
> }

Done

3.

> https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/gui/Display.java#L31-L36
> Calculate `Font `first and then set it once to swing component (avoid setting font multiple times)

Resize feature optimized with 'getFontMetrics' 

4.

> https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/gui/GUI.java#L67-L73
> Looks very hacky. This should be solved by proper configuration of LayoutManager.

Corrected confusing names, sole purpose of this is to adiust font size to user changes of frame.

5.

> https://github.com/EnQs/JustCalculator/blob/4844c8def1a60364c6fc9b5041b82a568abe28f4/src/gui/GUI.java#L26-L32
> Why are you passing var-args (array) instead string?

Just to give it a try, for now changed to sole String.
